spring:
  profile.active: dev
  datasource:
    url: jdbc:mysql://localhost/vollmed_api_test?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: Mimusica2804$
  jpa:
    hibernate:
      ddl-auto: update